version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  test-and-release:
    jobs:
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
      - release-management/test-nut:
          matrix:
            parameters:
              os:
                - linux
                - windows
              sfdx_version:
                - latest
              node_version:
                - latest
          requires:
            - release-management/test-package
      - release-management/release-package:
          github-release: true
          requires:
            - release-management/test-package
          filters:
            branches:
              only: main
